version: "3.9"
name: imtaiz-mart-api-template
services:
  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile.dev
    networks:
      - imtaiz_network
    volumes:
      - ./UserService:/code # Sync local development directory with the container
    depends_on:
      - db_user
      - broker
    ports:
      - "8010:8000" # Expose container port 8000 to host port 8000
  product-service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile.dev
    volumes:
      - ./ProductService:/code # Sync local development directory with the container
    depends_on:
      - db_product
      - broker
    networks:
      - imtaiz_network
    ports:
      - "8011:8000" # Expose container port 8000 to host port 8000
  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile.dev
    volumes:
      - ./OrderService:/code # Sync local development directory with the container
    depends_on:
      - db_order
      - broker
    networks:
      - imtaiz_network
    ports:
      - "8012:8000" # Expose container port 8000 to host port 8000
  db_user:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresUserCont
    environment:
      - POSTGRES_USER=shahidkhan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=imtaiz_user_db
    networks:
      - imtaiz_network
    ports:
      - "5433:5432"
    volumes:
      - imtaiz_user_db:/var/lib/postgresql/data
  db_product:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresProductCont
    environment:
      - POSTGRES_USER=shahidkhan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=imtaiz_product_db
    networks:
      - imtaiz_network
    ports:
      - "5434:5432"
    volumes:
      - imtaiz_product_db:/var/lib/postgresql/data
  db_order:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresOrderCont
    environment:
      - POSTGRES_USER=shahidkhan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=imtaiz_order_db
    networks:
      - imtaiz_network
    ports:
      - "5434:5432"
    volumes:
      - imtaiz_order_db:/var/lib/postgresql/data
  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    networks:
      - imtaiz_network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local Kafka Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:19092"
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker
    networks:
      - imtaiz_network
    # Schema Registry Service
  schema-registry:
    image: confluentinc/cp-schema-registry:6.1.1
    depends_on:
      - broker
    ports:
      - "8081:8081"
    networks:
      - imtaiz_network
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:19092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
volumes:
  imtaiz_user_db:
    driver: local
  imtaiz_product_db:
    driver: local
  imtaiz_order_db:
    driver: local
networks:
  imtaiz_network:
    driver: bridge
  default:
    driver: bridge
