version: "3.9"
name: imtaiz-mart-api-template

# kong start
x-kong-config:
  &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-postgres}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: db
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password

services:
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    profiles: [ "database" ]
    networks:
      - kong-net
    depends_on:
      - db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    restart: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    profiles: [ "database" ]
    networks:
      - kong-net
    depends_on:
      - db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    restart: on-failure

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    networks:
      - kong-net
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_ADMIN_GUI_LISTEN: "${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    secrets:
      - kong_postgres_password
    ports:
      # The following two environment variables default to an insecure value (0.0.0.0)
      # according to the CIS Security test.
      - "${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:8000:8000/tcp"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:8443:8443/tcp"
      # Making them mandatory but undefined, like so would be backwards-breaking:
      # - "${KONG_INBOUND_PROXY_LISTEN?Missing inbound proxy host}:8000:8000/tcp"
      # - "${KONG_INBOUND_SSL_PROXY_LISTEN?Missing inbound proxy ssl host}:8443:8443/tcp"
      # Alternative is deactivating check 5.13 in the security bench, if we consider Kong's own config to be enough security here

      - "127.0.0.1:8001:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
      - "127.0.0.1:8002:8002/tcp"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
      # - ./config:/opt/kong
    security_opt:
      - no-new-privileges

  db:
    image: postgres:9.5
    profiles: [ "database" ]
    networks:
      - kong-net
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${KONG_PG_DATABASE:-kong}",
          "-U",
          "${KONG_PG_USER:-kong}"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - kong_data:/var/lib/postgresql/data
# kong end
  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile.dev
    networks:
      - kong-net
    volumes:
      - ./UserService:/code # Sync local development directory with the container
    depends_on:
      - db_user
      - broker
    ports:
      - "8010:8085" # Expose container port 8085 to host port 8085
    restart: on-failure
  product-service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile.dev
    volumes:
      - ./ProductService:/code # Sync local development directory with the container
    depends_on:
      - db_product
      - broker
    networks:
      - kong-net
    ports:
      - "8011:8085" # Expose container port 8085 to host port 8085
    restart: on-failure
  inventory-service:
    build:
      context: ./InventoryService
      dockerfile: Dockerfile.dev
    volumes:
      - ./InventoryService:/code # Sync local development directory with the container
    depends_on:
      - db_inventory
      - broker
    networks:
      - kong-net
    ports:
      - "8012:8085" # Expose container port 8085 to host port 8085
  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile.dev
    volumes:
      - ./OrderService:/code # Sync local development directory with the container
    depends_on:
      - db_order
      - broker
    networks:
      - kong-net
    ports:
      - "8013:8085" # Expose container port 8000 to host port 8000
  db_user:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresUserCont
    environment:
      - POSTGRES_USER=shahidkhan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=imtaiz_user_db
    networks:
      - kong-net
    ports:
      - "5433:5432"
    volumes:
      - imtaiz_user_db:/var/lib/postgresql/data
  db_product:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresProductCont
    environment:
      - POSTGRES_USER=shahidkhan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=imtaiz_product_db
    networks:
      - kong-net
    ports:
      - "5434:5432"
    volumes:
      - imtaiz_product_db:/var/lib/postgresql/data
  db_inventory:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresInventoryCont
    environment:
      - POSTGRES_USER=shahidkhan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=imtaiz_inventory_db
    networks:
      - kong-net
    ports:
      - "5435:5432"
    volumes:
      - imtaiz_inventory_db:/var/lib/postgresql/data
  db_order:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresOrderCont
    environment:
      - POSTGRES_USER=shahidkhan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=imtaiz_order_db
    networks:
      - kong-net
    ports:
      - "5436:5432"
    volumes:
      - imtaiz_order_db:/var/lib/postgresql/data
  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    networks:
      - kong-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions --bootstrap-server broker:9092",
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local Kafka Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:19092"
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker
    networks:
      - kong-net
    # Schema Registry Service
  # schema-registry:
  #   image: confluentinc/cp-schema-registry:6.1.1
  #   depends_on:
  #     - broker
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - imtaiz_network
  #   environment:
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:19092
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

  imtaiz_user_db:
    driver: local
  imtaiz_product_db:
    driver: local
  imtaiz_order_db:
    driver: local
  imtaiz_inventory_db:
    driver: local
networks:
  kong-net:
    # external: false
    driver: bridge
  imtaiz_network:
    driver: bridge
  default:
    driver: bridge
secrets:
  kong_postgres_password:
    file: ./POSTGRES_PASSWORD