# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pp/proto/product.proto\x12\x07product\"\xdb\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ncategoryId\x18\x02 \x01(\x05\x12\x0f\n\x07\x62randId\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x12\r\n\x05title\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\x02\x12\x11\n\timage_url\x18\x08 \x01(\t\x12\x10\n\x08quantity\x18\t \x01(\x05\x12\x0e\n\x06rating\x18\n \x01(\x02\x12\x12\n\ncreated_at\x18\x0b \x01(\t\x12\x12\n\nupdated_at\x18\x0c \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=37
  _PRODUCT._serialized_end=256
# @@protoc_insertion_point(module_scope)
