# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token_validation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16token_validation.proto\x12\x0ftokenvalidation\"H\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"[\n\x10ValidationResult\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x19.tokenvalidation.UserData\">\n\x08UserData\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.tokenvalidation.User\x12\r\n\x05roles\x18\x02 \x03(\t\"U\n\x15ValidateTokenResponse\x12<\n\x11validation_result\x18\x01 \x01(\x0b\x32!.tokenvalidation.ValidationResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'token_validation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=43
  _USER._serialized_end=115
  _VALIDATIONRESULT._serialized_start=117
  _VALIDATIONRESULT._serialized_end=208
  _USERDATA._serialized_start=210
  _USERDATA._serialized_end=272
  _VALIDATETOKENRESPONSE._serialized_start=274
  _VALIDATETOKENRESPONSE._serialized_end=359
# @@protoc_insertion_point(module_scope)
